In [2]:
import torch
import json
import os

/home/chenyang/software/miniconda3/envs/ccks/lib/python3.6/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
obj_info = json.load(open("../data/CSDQA_3/img2obj.json"))

In [4]:
obj_info

{'007.png': [{'shape_attributes': {'name': 'rect',
    'x': 111,
    'y': 34,
    'width': 42,
    'height': 33},
   'region_attributes': {'Type': {'object': True},
    'Obj_id': '1',
    'Obj_label': 'pop element',
    'Description': 'An element ready to be popped in the stack, whose value is 5.',
    'Logic_id': '',
    'Logic_label': '',
    'Relationship': ''}},
  {'shape_attributes': {'name': 'rect',
    'x': 37,
    'y': 106,
    'width': 44,
    'height': 33},
   'region_attributes': {'Type': {'object': True},
    'Obj_id': '2',
    'Obj_label': 'top element',
    'Description': 'An element in the stack. whose value is 4.',
    'Logic_id': '',
    'Logic_label': '',
    'Relationship': ''}},
  {'shape_attributes': {'name': 'rect',
    'x': 38,
    'y': 139,
    'width': 43,
    'height': 29},
   'region_attributes': {'Type': {'object': True},
    'Obj_id': '3',
    'Obj_label': 'internal element',
    'Description': 'An element in the stack. whose value is 3.',
    'Logic_id': '

In [5]:
"An element ready to be popped is in the stack, whose value is 5.".rfind("is")

59

In [6]:
"An element ready to be popped is in the stack, whose value is 5."[62]

'5'

In [58]:
obj_json = json.load(open("../data/CSDQA_3/img2obj.json"))
num = 0
count = 0
min_num = 1e9
max_num = 0
for pic, pic_info in obj_json.items():
    for info in pic_info[:55]:
        count += 1
        desc = info["region_attributes"]['Description']
        if desc != '':
            index = desc.rfind("is") + 3
            assert index < desc.__len__(), print(info)
            if desc[index] == '-' or desc[index] in ['0','1','2','3','4','5','6','7','8','9']:
                num += 1
                if desc[index] == '-' and desc[index+1] not in ['0','1','2','3','4','5','6','7','8','9']:
                    print(desc[index:], "   ", pic)
                else:
                    try:
                        if max_num < int(desc[index:-1]):
                            max_num = int(desc[index:-1])
                        if min_num > int(desc[index:-1]):
                            min_num = int(desc[index:-1])
                    except ValueError:
                        pass
        else:
            continue

-.     128.png
-.     129.png


In [59]:
obj_json.__len__()

324

In [60]:
count

1226

In [61]:
max_num

2011

In [62]:
min_num

-7

In [63]:
num

809

In [3]:
a = torch.arange(10).expand((1, -1))
a

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [4]:
a[:, : 10]

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [11]:
desc = "An element ready to be popped is 10 in the stack, whose value is ."

if desc != '':
    index = desc.rfind("is") + 3
    assert index < desc.__len__(), print(info)
    if desc[index] == '-' or desc[index] in ['0','1','2','3','4','5','6','7','8','9']:
        if desc[index] == '-' and desc[index+1] not in ['0','1','2','3','4','5','6','7','8','9']:
            desc_weight = 0
        else:
            try:
                desc_weight = int(desc[index:-1])
            except ValueError:
                desc_weight = 0
    else:
        desc_weight = 0
else:
    desc_weight = 0
desc_weight

0

In [2]:
import os, sys

In [3]:
os.path.abspath(__file__)

NameError: name '__file__' is not defined

In [6]:
a = torch.tensor([[1, 2, 3]])

In [7]:
a

tensor([[1, 2, 3]])

In [8]:
a.size()

torch.Size([1, 3])

In [9]:
a.dim()

2